In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
BB = pd.read_csv('BigBasket Products.csv')
print(BB.head())

   index                                            product  \
0      1             Garlic Oil - Vegetarian Capsule 500 mg
1      2                              Water Bottle - Orange
2      3                     Brass Angle Deep - Plain, No.2
3      4  Cereal Flip Lid Container/Storage Jar - Assort...
4      5                 Creme Soft Soap - For Hands & Body

                 category           sub_category              brand  \
0        Beauty & Hygiene              Hair Care  Sri Sri Ayurveda
1  Kitchen, Garden & Pets  Storage & Accessories         Mastercook
2    Cleaning & Household            Pooja Needs                Trm
3    Cleaning & Household   Bins & Bathroom Ware             Nakoda
4        Beauty & Hygiene       Bath & Hand Wash              Nivea

   sale_price  market_price                      type  rating  \
0       220.0         220.0          Hair Oil & Serum     4.1
1       180.0         180.0    Water & Fridge Bottles     2.3
2       119.0         250.0           Lamp & Lamp Oil     3.4
3       149.0         176.0  Laundry, Storage Baskets     3.7
4       162.0         162.0      Bathing Bars & Soaps     4.4

                                         description
0  This Product contains Garlic Oil that is known...
1  Each product is microwave safe (without lid), ...
2  A perfect gift for all occasions, be it your m...
3  Multipurpose container with an attractive desi...
4  Nivea Creme Soft Soap gives your skin the best...

In [8]:
BB.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27555 entries, 0 to 27554
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   index         27555 non-null  int64
 1   product       27554 non-null  object
 2   category      27555 non-null  object
 3   sub_category  27555 non-null  object
 4   brand         27554 non-null  object
 5   sale_price    27555 non-null  float64
 6   market_price  27555 non-null  float64
 7   type          27555 non-null  object
 8   rating        18929 non-null  float64
 9   description   27440 non-null  object
dtypes: float64(3), int64(1), object(6)
memory usage: 2.1+ MB

In [9]:
BB.isnull().sum()

index              0
product            1
category           0
sub_category       0
brand              1
sale_price         0
market_price       0
type               0
rating          8626
description      115
dtype: int64

In [10]:
BB.describe()

             index    sale_price  market_price        rating
count  27555.00000  27555.000000  27555.000000  18929.000000
mean   13778.00000    322.514808    382.056664      3.943410
std     7954.58767    486.263116    581.730717      0.739063
min        1.00000      2.450000      3.000000      1.000000
25%     6889.50000     95.000000    100.000000      3.700000
50%    13778.00000    190.000000    220.000000      4.100000
75%    20666.50000    359.000000    425.000000      4.300000
max    27555.00000  12500.000000  12500.000000      5.000000

In [11]:
# Fill with mean (numeric)
BB['sale_price'] = BB['sale_price'].fillna(BB['sale_price'].mean())
BB['market_price'] = BB['market_price'].fillna(BB['market_price'].mean())
# Fill with mode (categorical)
BB['product'] = BB['product'].fillna(BB['product'].mode()[0])

# Drop rows with missing values
BB = BB.dropna()

In [12]:
BB = BB.drop_duplicates()

In [13]:
# Remove extreme values using percentile
q_low = BB['sale_price'].quantile(0.01)
q_high = BB['sale_price'].quantile(0.99)

df = BB[(BB['sale_price'] >= q_low) & (BB['sale_price'] <= q_high)]

In [14]:
# Remove extreme values using percentile
q_low = BB['market_price'].quantile(0.01)
q_high = BB['market_price'].quantile(0.99)

df = BB[(BB['market_price'] >= q_low) & (BB['market_price'] <= q_high)]

In [15]:
# Remove extra spaces
df['product'] = df['product'].str.strip()

# Convert to lowercase
df['product'] = df['product'].str.lower()

In [17]:
# Example: Discount %
df['discount_percent'] = ((df['market_price'] - df['sale_price']) / df['market_price']) * 100

In [23]:
df.to_csv("cleaned_bigbasket_data.csv", index=False)